import * as z from 'zod';

/**
 * @see AutomationScope
 */
export const AutomationScopeSchema = z.enum(['Write', 'Submit']);

/**
 * Defines the scope of permissions for automation access keys (editor or submitter).
 * @type AutomationScope
 */
export type AutomationScope = z.infer<typeof AutomationScopeSchema>;

/**
 * @see AutomationAccessKeysConfig
 */
export const AutomationAccessKeysConfigSchema = z.strictObject({
  scope: AutomationScopeSchema.optional(),
  timeToLive: z
    .bigint()
    .max(
      60n * 60n * 1_000_000_000n,
      'The maximal length of a defined session duration - maxTimeToLive - cannot exceed 1 hour'
    )
    .optional()
});

/**
 * Configure the controller behavior for automation.
 *
 * @interface AutomationAccessKeysConfig
 */
export interface AutomationAccessKeysConfig {
  /**
   * The scope of permissions granted to the automation access keys.
   *
   * If omitted, defaults to `Write`.
   */
  scope?: AutomationScope;

  /**
   * Duration for which an automation access key remains valid, expressed in nanoseconds.
   *
   * Defaults to 10 minutes. Cannot exceed 1 hour.
   */
  timeToLive?: bigint;
}

/**
 * @see AutomationConfigRepository
 */
export const AutomationConfigRepositorySchema = z.strictObject({
  owner: z
    .string()
    .trim()
    .min(1, 'Repository owner cannot be empty')
    .max(256, 'Repository owner too long'),
  name: z
    .string()
    .trim()
    .min(1, 'Repository name cannot be empty')
    .max(256, 'Repository name too long'),
  branches: z.array(z.string().trim().min(1)).optional()
});

/**
 * Configure repository access for automation.
 *
 * @interface AutomationConfigRepository
 */
export interface AutomationConfigRepository {
  /**
   * Repository owner (e.g. "octo-org" or "peterpeterparker" for GitHub).
   *
   * @type {string}
   */
  owner: string;

  /**
   * Repository name (e.g, "octo-repo" or "daviddalbusco.com" for GitHub).
   *
   * @type {string}
   */
  name: string;

  /**
   * Optional list of allowed branches (e.g., ["main", "develop"]).
   *
   * If omitted, all branches are allowed.
   *
   * @type {string[]}
   * @optional
   */
  branches?: string[];
}

/**
 * @see AutomationConfigGitHub
 */
export const AutomationConfigGitHubSchema = z.strictObject({
  repositories: z
    .array(AutomationConfigRepositorySchema)
    .min(1, 'At least one repository required')
    .refine(
      (repos) => {
        const keys = repos.map((r) => `${r.owner}/${r.name}`);
        return keys.length === new Set(keys).size;
      },
      {message: 'Duplicate repositories are not allowed'}
    ),
  accessKeys: AutomationAccessKeysConfigSchema.optional()
});

/**
 * Configure automation via GitHub Actions.
 *
 * @interface AutomationConfigGitHub
 */
export interface AutomationConfigGitHub {
  /**
   * List of GitHub repositories authorized to authenticate with this Satellite.
   *
   * Each repository must specify owner and name.
   * Optionally restrict to specific branches.
   *
   * @type {AutomationConfigRepository[]}
   */
  repositories: AutomationConfigRepository[];

  /**
   * Optional configuration for the access keys generated by the automation.
   * If omitted, default behavior applies.
   *
   * @type {AutomationAccessKeysConfig}
   * @optional
   */
  accessKeys?: AutomationAccessKeysConfig;
}

/**
 * @see AutomationConfig
 */
export const AutomationConfigSchema = z.strictObject({
  github: AutomationConfigGitHubSchema.optional(),
  version: z.bigint().optional()
});

/**
 * Configures the Automation options of a Satellite.
 * @interface AutomationConfig
 */
export interface AutomationConfig {
  /**
   * Optional configuration for enabling automation through GitHub Actions.
   *
   * @type {AutomationConfigGitHub}
   * @optional
   */
  github?: AutomationConfigGitHub;

  /**
   * The current version of the config.
   *
   * Optional. The CLI will automatically resolve the version and warn you if there's a potential overwrite.
   * You can provide it if you want to manage versioning manually within your config file.
   *
   * @type {bigint}
   * @optional
   */
  version?: bigint;
}
