import {FRONTEND_FUNCTION_NAMESPACE} from '../../../constants';
import {templateNamespace} from '../../_contants';
import type {TransformerOptions} from '../../types/transformer-options';
import type {MethodSignature} from '../types/method-signature';

const template = `// This file was automatically generated by the Juno CLI.
// Any modifications may be overwritten.

/* eslint-disable */
/* prettier-ignore */
%IMPORT%
import {idlFactory} from './satellite.factory.did.js';
import {getSatelliteExtendedActor} from '@junobuild/%CORE_LIB%';

%METHODS%

%NAMESPACE%
`;

const methodTemplateTypeScript = `const %METHOD_NAME% = async (%PARAMS%): Promise<%METHOD_RESULT%> => {
\tconst {%DID_METHOD_NAME%} = await getSatelliteExtendedActor<SatelliteActor>({
\t\tidlFactory
\t});

\treturn await %DID_METHOD_NAME%(%CALL_PARAMS%);
}`;

const methodTemplateJavaScript = `const %METHOD_NAME% = async (%CALL_PARAMS%) => {
\tconst {%DID_METHOD_NAME%} = await getSatelliteExtendedActor({
\t\tidlFactory
\t});

\treturn await %DID_METHOD_NAME%(%CALL_PARAMS%);
}`;

const importTemplateTypeScript = `
import type {_SERVICE as SatelliteActor%IMPORTS%} from './satellite.did';
import type { Principal } from '@icp-sdk/core/principal';`;

export const parseApi = ({
  methods: signatures,
  imports,
  transformerOptions: {coreLib, outputLanguage}
}: {
  methods: MethodSignature[];
  imports: string[];
  transformerOptions: TransformerOptions;
}): string => {
  const langTemplate =
    outputLanguage === 'js' ? methodTemplateJavaScript : methodTemplateTypeScript;

  const replacers = signatures.map(mapSignature);

  const methods = replacers
    .map((replacer) => {
      let result = langTemplate;
      Object.entries(replacer).map(([key, value]) => {
        result = result.replaceAll(`%${key}%`, value);
      });

      return result;
    })
    .join('\n\n');

  const namespaceExport = templateNamespace
    .replace('%FUNCTION_NAMESPACE%', FRONTEND_FUNCTION_NAMESPACE)
    .replace('%JS_FUNCTIONS%', replacers.map(({METHOD_NAME}) => METHOD_NAME).join(',\n\t'));

  return template
    .replace('%CORE_LIB%', coreLib ?? 'core')
    .replace('%METHODS%', methods)
    .replace('%NAMESPACE%', namespaceExport)
    .replace(
      '%IMPORT%',
      outputLanguage === 'js'
        ? ''
        : importTemplateTypeScript.replace(
            '%IMPORTS%',
            imports.length === 0 ? '' : `, ${imports.join(', ')}`
          )
    )
    .trim();
};

interface Replacer {
  METHOD_NAME: string;
  DID_METHOD_NAME: string;
  METHOD_RESULT: string;
  PARAMS: string;
  CALL_PARAMS: string;
}

const mapSignature = ({name, returnType, paramsType}: MethodSignature): Replacer => {
  const camelize = (s: string): string => s.replace(/_./g, (x) => x[1].toUpperCase());

  const methodName = camelize(name);

  const params = paramsType.map((paramType, i) => ({
    param: `value${i}`,
    type: paramType
  }));

  const paramKeysText = `${params.map(({param}) => param).join(', ')}`;

  const paramsText = params.map(({param, type}) => `${param}: ${type}`).join(', ');

  return {
    METHOD_NAME: methodName,
    DID_METHOD_NAME: name,
    METHOD_RESULT: returnType,
    PARAMS: paramsText,
    CALL_PARAMS: paramKeysText
  };
};
