import {parseZodApi} from '../../../../api/zod/services/parser.services';
import {
  mockJsFullNoArgsNoResult,
  mockJsNoArgsNoResult,
  mockJsNoArgsWithResult,
  mockJsWithArgsNoResult,
  mockJsWithArgsWithResult,
  mockTsFullNoArgsNoResult,
  mockTsNoArgsNoResult,
  mockTsNoArgsWithResult,
  mockTsWithArgsNoResult,
  mockTsWithArgsWithResult
} from '../mocks/zod-api-transformed.mock';
import {
  mockQueryNoArgsNoResult,
  mockQueryNoArgsWithResult,
  mockQueryWithArgsNoResult,
  mockQueryWithArgsWithResult,
  mockQueryWithArray,
  mockQueryWithEnum,
  mockQueryWithNestedObject,
  mockQueryWithPrincipal,
  mockQueryWithUint8Array
} from '../mocks/zod-api.mock';

describe('zod-api-parser', () => {
  // ─── file header ────────────────────────────────────────────────────────────

  describe('file header', () => {
    it('should include generated comment', () => {
      const result = parseZodApi({
        queries: [['helloWorld', mockQueryNoArgsNoResult]],
        updates: [],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain('// This file was automatically generated by the Juno CLI.');
      expect(result).toContain('// Any modifications may be overwritten.');
    });

    it('should import SatelliteActor from satellite.did for ts', () => {
      const result = parseZodApi({
        queries: [['helloWorld', mockQueryNoArgsNoResult]],
        updates: [],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain("import type {_SERVICE as SatelliteActor} from './satellite.did';");
    });

    it('should not import SatelliteActor for js', () => {
      const result = parseZodApi({
        queries: [['helloWorld', mockQueryNoArgsNoResult]],
        updates: [],
        transformerOptions: {outputLanguage: 'js'}
      });
      expect(result).not.toContain('import type {_SERVICE as SatelliteActor}');
    });

    it('should import z from zod for ts', () => {
      const result = parseZodApi({
        queries: [['helloWorld', mockQueryNoArgsNoResult]],
        updates: [],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain("import * as z from 'zod';");
    });

    it('should import z from zod for js', () => {
      const result = parseZodApi({
        queries: [['helloWorld', mockQueryNoArgsNoResult]],
        updates: [],
        transformerOptions: {outputLanguage: 'js'}
      });
      expect(result).toContain("import * as z from 'zod';");
    });

    it('should import recursiveToNullable and recursiveFromNullable', () => {
      const result = parseZodApi({
        queries: [['helloWorld', mockQueryWithArgsWithResult]],
        updates: [],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain(
        "import {recursiveToNullable, recursiveFromNullable} from '@junobuild/zod';"
      );
    });

    it('should import from core by default', () => {
      const result = parseZodApi({
        queries: [['helloWorld', mockQueryNoArgsNoResult]],
        updates: [],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain("import {getSatelliteExtendedActor} from '@junobuild/core';");
    });

    it('should import from core-standalone when specified', () => {
      const result = parseZodApi({
        queries: [['helloWorld', mockQueryNoArgsNoResult]],
        updates: [],
        transformerOptions: {outputLanguage: 'ts', coreLib: 'core-standalone'}
      });
      expect(result).toContain(
        "import {getSatelliteExtendedActor} from '@junobuild/core-standalone';"
      );
    });

    it('should import idlFactory from satellite.factory.did.js', () => {
      const result = parseZodApi({
        queries: [['helloWorld', mockQueryNoArgsNoResult]],
        updates: [],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain("import {idlFactory} from './satellite.factory.did.js';");
    });

    it('should import idlFactory from satellite.factory.did.js for js', () => {
      const result = parseZodApi({
        queries: [['helloWorld', mockQueryNoArgsNoResult]],
        updates: [],
        transformerOptions: {outputLanguage: 'js'}
      });
      expect(result).toContain("import {idlFactory} from './satellite.factory.did.js';");
    });
  });

  // ─── no args no result ───────────────────────────────────────────────────────

  describe('no args no result', () => {
    it('should generate ts function with no args and no result', () => {
      const result = parseZodApi({
        queries: [['helloWorld', mockQueryNoArgsNoResult]],
        updates: [],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain('export const helloWorld = async (): Promise<void>');
      expect(result).toContain('await app_hello_world();');
      expect(result).not.toContain('AppHelloWorldArgsSchema');
      expect(result).not.toContain('AppHelloWorldResultSchema');
    });

    it('should generate js function with no args and no result', () => {
      const result = parseZodApi({
        queries: [['helloWorld', mockQueryNoArgsNoResult]],
        updates: [],
        transformerOptions: {outputLanguage: 'js'}
      });
      expect(result).toContain('export const helloWorld = async ()');
      expect(result).not.toContain(': Promise<void>');
      expect(result).toContain('await app_hello_world();');
    });
  });

  // ─── args only ───────────────────────────────────────────────────────────────

  describe('args only', () => {
    it('should generate ts function with args and no result', () => {
      const result = parseZodApi({
        queries: [['helloWorld', mockQueryWithArgsNoResult]],
        updates: [],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain(
        'const AppHelloWorldArgsSchema = z.strictObject({name: z.string()});'
      );
      expect(result).toContain('args: z.infer<typeof AppHelloWorldArgsSchema>');
      expect(result).toContain(': Promise<void>');
      expect(result).toContain(
        'recursiveToNullable({schema: AppHelloWorldArgsSchema, value: parsedArgs})'
      );
      expect(result).not.toContain('AppHelloWorldResultSchema');
    });

    it('should generate js function with args and no result', () => {
      const result = parseZodApi({
        queries: [['helloWorld', mockQueryWithArgsNoResult]],
        updates: [],
        transformerOptions: {outputLanguage: 'js'}
      });
      expect(result).toContain(
        'const AppHelloWorldArgsSchema = z.strictObject({name: z.string()});'
      );
      expect(result).toContain('export const helloWorld = async (args)');
      expect(result).not.toContain(': Promise<void>');
      expect(result).not.toContain('AppHelloWorldResultSchema');
    });
  });

  // ─── result only ─────────────────────────────────────────────────────────────

  describe('result only', () => {
    it('should generate ts function with no args and result', () => {
      const result = parseZodApi({
        queries: [['helloWorld', mockQueryNoArgsWithResult]],
        updates: [],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain(
        'const AppHelloWorldResultSchema = z.strictObject({value: z.string()});'
      );
      expect(result).toContain('Promise<z.infer<typeof AppHelloWorldResultSchema>>');
      expect(result).toContain(
        'recursiveFromNullable({schema: AppHelloWorldResultSchema, value: idlResult})'
      );
      expect(result).toContain('return AppHelloWorldResultSchema.parse(result);');
      expect(result).not.toContain('AppHelloWorldArgsSchema');
    });

    it('should generate js function with no args and result', () => {
      const result = parseZodApi({
        queries: [['helloWorld', mockQueryNoArgsWithResult]],
        updates: [],
        transformerOptions: {outputLanguage: 'js'}
      });
      expect(result).toContain(
        'const AppHelloWorldResultSchema = z.strictObject({value: z.string()});'
      );
      expect(result).toContain('export const helloWorld = async ()');
      expect(result).not.toContain('Promise<');
      expect(result).not.toContain('AppHelloWorldArgsSchema');
    });
  });

  // ─── args and result ─────────────────────────────────────────────────────────

  describe('args and result', () => {
    it('should generate ts function with args and result', () => {
      const result = parseZodApi({
        queries: [['helloWorld', mockQueryWithArgsWithResult]],
        updates: [],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain(
        'const AppHelloWorldArgsSchema = z.strictObject({name: z.string(), age: z.optional(z.int())});'
      );
      expect(result).toContain(
        'const AppHelloWorldResultSchema = z.strictObject({value: z.string(), count: z.bigint()});'
      );
      expect(result).toContain('args: z.infer<typeof AppHelloWorldArgsSchema>');
      expect(result).toContain('Promise<z.infer<typeof AppHelloWorldResultSchema>>');
      expect(result).toContain(
        'recursiveToNullable({schema: AppHelloWorldArgsSchema, value: parsedArgs})'
      );
      expect(result).toContain(
        'recursiveFromNullable({schema: AppHelloWorldResultSchema, value: idlResult})'
      );
      expect(result).toContain('return AppHelloWorldResultSchema.parse(result);');
    });

    it('should generate js function with args and result', () => {
      const result = parseZodApi({
        queries: [['helloWorld', mockQueryWithArgsWithResult]],
        updates: [],
        transformerOptions: {outputLanguage: 'js'}
      });
      expect(result).toContain('const AppHelloWorldArgsSchema');
      expect(result).toContain('const AppHelloWorldResultSchema');
      expect(result).toContain('export const helloWorld = async (args)');
      expect(result).not.toContain(': Promise<');
      expect(result).not.toContain('z.infer<');
    });
  });

  // ─── rs function name ────────────────────────────────────────────────────────

  describe('rs function name', () => {
    it('should convert camelCase to snake_case with namespace prefix', () => {
      const result = parseZodApi({
        queries: [['helloWorld', mockQueryNoArgsNoResult]],
        updates: [],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain('app_hello_world');
    });

    it('should handle single word function name', () => {
      const result = parseZodApi({
        queries: [['greet', mockQueryNoArgsNoResult]],
        updates: [],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain('app_greet');
    });

    it('should handle long camelCase function name', () => {
      const result = parseZodApi({
        queries: [['getSatelliteConfig', mockQueryNoArgsNoResult]],
        updates: [],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain('app_get_satellite_config');
    });
  });

  // ─── schema naming ───────────────────────────────────────────────────────────

  describe('schema naming', () => {
    it('should prefix schema with FUNCTION_NAMESPACE and capitalize', () => {
      const result = parseZodApi({
        queries: [['helloWorld', mockQueryWithArgsWithResult]],
        updates: [],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain('AppHelloWorldArgsSchema');
      expect(result).toContain('AppHelloWorldResultSchema');
    });

    it('should handle single word function name in schema', () => {
      const result = parseZodApi({
        queries: [['greet', mockQueryWithArgsWithResult]],
        updates: [],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain('AppGreetArgsSchema');
      expect(result).toContain('AppGreetResultSchema');
    });
  });

  // ─── queries vs updates ──────────────────────────────────────────────────────

  describe('queries vs updates', () => {
    it('should generate functions for queries', () => {
      const result = parseZodApi({
        queries: [['helloWorld', mockQueryWithArgsWithResult]],
        updates: [],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain('export const helloWorld');
    });

    it('should generate functions for updates', () => {
      const result = parseZodApi({
        queries: [],
        updates: [['helloWorld', mockQueryWithArgsWithResult]],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain('export const helloWorld');
    });

    it('should generate functions for both queries and updates', () => {
      const result = parseZodApi({
        queries: [['getUser', mockQueryNoArgsWithResult]],
        updates: [['setUser', mockQueryWithArgsNoResult]],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain('export const getUser');
      expect(result).toContain('export const setUser');
    });

    it('should handle empty queries and updates', () => {
      const result = parseZodApi({
        queries: [],
        updates: [],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain('// This file was automatically generated');
      expect(result).not.toContain('export const');
    });
  });

  // ─── multiple functions ──────────────────────────────────────────────────────

  describe('multiple functions', () => {
    it('should generate multiple query functions', () => {
      const result = parseZodApi({
        queries: [
          ['getUser', mockQueryNoArgsWithResult],
          ['listUsers', mockQueryNoArgsWithResult],
          ['searchUsers', mockQueryWithArgsWithResult]
        ],
        updates: [],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain('export const getUser');
      expect(result).toContain('export const listUsers');
      expect(result).toContain('export const searchUsers');
    });

    it('should generate multiple update functions', () => {
      const result = parseZodApi({
        queries: [],
        updates: [
          ['createUser', mockQueryWithArgsNoResult],
          ['deleteUser', mockQueryWithArgsNoResult]
        ],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain('export const createUser');
      expect(result).toContain('export const deleteUser');
    });
  });

  // ─── schema types ────────────────────────────────────────────────────────────

  describe('schema types', () => {
    it('should handle principal in args', () => {
      const result = parseZodApi({
        queries: [['helloWorld', mockQueryWithPrincipal]],
        updates: [],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain('PrincipalSchema');
    });

    it('should handle Uint8Array in args', () => {
      const result = parseZodApi({
        queries: [['helloWorld', mockQueryWithUint8Array]],
        updates: [],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain('Uint8ArraySchema');
    });

    it('should handle array fields', () => {
      const result = parseZodApi({
        queries: [['helloWorld', mockQueryWithArray]],
        updates: [],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain('z.array(z.string())');
    });

    it('should handle enum fields', () => {
      const result = parseZodApi({
        queries: [['helloWorld', mockQueryWithEnum]],
        updates: [],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain("z.enum(['active', 'inactive'])");
    });

    it('should handle nested objects', () => {
      const result = parseZodApi({
        queries: [['helloWorld', mockQueryWithNestedObject]],
        updates: [],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain(
        'z.strictObject({street: z.string(), city: z.optional(z.string())})'
      );
    });
  });

  // ─── full output ─────

  describe('full output', () => {
    it('should match ts no args no result', () => {
      const result = parseZodApi({
        queries: [['helloWorld', mockQueryNoArgsNoResult]],
        updates: [],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result.trim()).toContain(mockTsNoArgsNoResult);
    });

    it('should match ts with args no result', () => {
      const result = parseZodApi({
        queries: [['helloWorld', mockQueryWithArgsNoResult]],
        updates: [],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result.trim()).toContain(mockTsWithArgsNoResult);
    });

    it('should match ts no args with result', () => {
      const result = parseZodApi({
        queries: [['helloWorld', mockQueryNoArgsWithResult]],
        updates: [],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result.trim()).toContain(mockTsNoArgsWithResult);
    });

    it('should match ts with args and result', () => {
      const result = parseZodApi({
        queries: [['helloWorld', mockQueryWithArgsWithResult]],
        updates: [],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result.trim()).toContain(mockTsWithArgsWithResult);
    });

    it('should match js no args no result', () => {
      const result = parseZodApi({
        queries: [['helloWorld', mockQueryNoArgsNoResult]],
        updates: [],
        transformerOptions: {outputLanguage: 'js'}
      });
      expect(result.trim()).toContain(mockJsNoArgsNoResult);
    });

    it('should match js with args no result', () => {
      const result = parseZodApi({
        queries: [['helloWorld', mockQueryWithArgsNoResult]],
        updates: [],
        transformerOptions: {outputLanguage: 'js'}
      });
      expect(result.trim()).toContain(mockJsWithArgsNoResult);
    });

    it('should match js no args with result', () => {
      const result = parseZodApi({
        queries: [['helloWorld', mockQueryNoArgsWithResult]],
        updates: [],
        transformerOptions: {outputLanguage: 'js'}
      });
      expect(result.trim()).toContain(mockJsNoArgsWithResult);
    });

    it('should match js with args and result', () => {
      const result = parseZodApi({
        queries: [['helloWorld', mockQueryWithArgsWithResult]],
        updates: [],
        transformerOptions: {outputLanguage: 'js'}
      });
      expect(result.trim()).toContain(mockJsWithArgsWithResult);
    });

    it('should match full ts output no args no result', () => {
      const result = parseZodApi({
        queries: [['helloWorld', mockQueryNoArgsNoResult]],
        updates: [],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result.trim()).toEqual(mockTsFullNoArgsNoResult);
    });

    it('should match full js output no args no result', () => {
      const result = parseZodApi({
        queries: [['helloWorld', mockQueryNoArgsNoResult]],
        updates: [],
        transformerOptions: {outputLanguage: 'js'}
      });
      expect(result.trim()).toEqual(mockJsFullNoArgsNoResult);
    });
  });
});
