export const mockTsNoArgsNoResult = `const helloWorld = async (): Promise<void> => {
\tconst {app_hello_world} = await getSatelliteExtendedActor<SatelliteActor>({idlFactory});
\tawait app_hello_world();
};`;

export const mockTsWithArgsNoResult = `const AppHelloWorldArgsSchema = z.strictObject({name: z.string()});

const helloWorld = async (args: z.infer<typeof AppHelloWorldArgsSchema>): Promise<void> => {
\tconst parsedArgs = AppHelloWorldArgsSchema.parse(args);
\tconst idlArgs = recursiveToNullable({schema: AppHelloWorldArgsSchema, value: parsedArgs});

\tconst {app_hello_world} = await getSatelliteExtendedActor<SatelliteActor>({idlFactory});
\tawait app_hello_world(idlArgs);
};`;

export const mockTsNoArgsWithResult = `const AppHelloWorldResultSchema = z.strictObject({value: z.string()});

const helloWorld = async (): Promise<z.infer<typeof AppHelloWorldResultSchema>> => {
\tconst {app_hello_world} = await getSatelliteExtendedActor<SatelliteActor>({idlFactory});
\tconst idlResult = await app_hello_world();

\tconst result = recursiveFromNullable({schema: AppHelloWorldResultSchema, value: idlResult});
\treturn AppHelloWorldResultSchema.parse(result);
};`;

export const mockTsWithArgsWithResult = `const AppHelloWorldArgsSchema = z.strictObject({name: z.string(), age: z.optional(z.int())});
const AppHelloWorldResultSchema = z.strictObject({value: z.string(), count: z.bigint()});

const helloWorld = async (args: z.infer<typeof AppHelloWorldArgsSchema>): Promise<z.infer<typeof AppHelloWorldResultSchema>> => {
\tconst parsedArgs = AppHelloWorldArgsSchema.parse(args);
\tconst idlArgs = recursiveToNullable({schema: AppHelloWorldArgsSchema, value: parsedArgs});

\tconst {app_hello_world} = await getSatelliteExtendedActor<SatelliteActor>({idlFactory});
\tconst idlResult = await app_hello_world(idlArgs);

\tconst result = recursiveFromNullable({schema: AppHelloWorldResultSchema, value: idlResult});
\treturn AppHelloWorldResultSchema.parse(result);
};`;

export const mockJsNoArgsNoResult = `const helloWorld = async () => {
\tconst {app_hello_world} = await getSatelliteExtendedActor({idlFactory});
\tawait app_hello_world();
};`;

export const mockJsWithArgsNoResult = `const AppHelloWorldArgsSchema = z.strictObject({name: z.string()});

const helloWorld = async (args) => {
\tconst parsedArgs = AppHelloWorldArgsSchema.parse(args);
\tconst idlArgs = recursiveToNullable({schema: AppHelloWorldArgsSchema, value: parsedArgs});

\tconst {app_hello_world} = await getSatelliteExtendedActor({idlFactory});
\tawait app_hello_world(idlArgs);
};`;

export const mockJsNoArgsWithResult = `const AppHelloWorldResultSchema = z.strictObject({value: z.string()});

const helloWorld = async () => {
\tconst {app_hello_world} = await getSatelliteExtendedActor({idlFactory});
\tconst idlResult = await app_hello_world();

\tconst result = recursiveFromNullable({schema: AppHelloWorldResultSchema, value: idlResult});
\treturn AppHelloWorldResultSchema.parse(result);
};`;

export const mockJsWithArgsWithResult = `const AppHelloWorldArgsSchema = z.strictObject({name: z.string(), age: z.optional(z.int())});
const AppHelloWorldResultSchema = z.strictObject({value: z.string(), count: z.bigint()});

const helloWorld = async (args) => {
\tconst parsedArgs = AppHelloWorldArgsSchema.parse(args);
\tconst idlArgs = recursiveToNullable({schema: AppHelloWorldArgsSchema, value: parsedArgs});

\tconst {app_hello_world} = await getSatelliteExtendedActor({idlFactory});
\tconst idlResult = await app_hello_world(idlArgs);

\tconst result = recursiveFromNullable({schema: AppHelloWorldResultSchema, value: idlResult});
\treturn AppHelloWorldResultSchema.parse(result);
};`;

export const mockTsFullNoArgsNoResult = `// This file was automatically generated by the Juno CLI.
// Any modifications may be overwritten.

/* eslint-disable */
/* prettier-ignore */

import type {_SERVICE as SatelliteActor} from './satellite.did';
import {idlFactory} from './satellite.factory.did.js';
import {getSatelliteExtendedActor} from '@junobuild/core';
import {recursiveToNullable, recursiveFromNullable} from '@junobuild/zod';
import * as z from 'zod';

const helloWorld = async (): Promise<void> => {
\tconst {app_hello_world} = await getSatelliteExtendedActor<SatelliteActor>({idlFactory});
\tawait app_hello_world();
};

export const functions = {
\thelloWorld
};`;

export const mockJsFullNoArgsNoResult = `// This file was automatically generated by the Juno CLI.
// Any modifications may be overwritten.

/* eslint-disable */
/* prettier-ignore */

import {idlFactory} from './satellite.factory.did.js';
import {getSatelliteExtendedActor} from '@junobuild/core';
import {recursiveToNullable, recursiveFromNullable} from '@junobuild/zod';
import * as z from 'zod';

const helloWorld = async () => {
\tconst {app_hello_world} = await getSatelliteExtendedActor({idlFactory});
\tawait app_hello_world();
};

export const functions = {
\thelloWorld
};`;
