import type {Query, Update} from '@junobuild/functions';

const template = `// This file was automatically generated by the Juno CLI.
// Any modifications may be overwritten.
#![allow(unused)]

use crate::functions::{
    execute_async_function, execute_sync_function,
    types::{NoArgs, NoResult},
};
use candid::{CandidType, Principal};
use junobuild_macros::JsonData;
use junobuild_shared::ic::UnwrapOrTrap;
use junobuild_shared::ic::UnwrapOrTrapResult;
use serde::{Deserialize, Serialize};

%FUNCTIONS%
`;

const templateSyncQuery = `#[ic_cdk::query]
fn %RS_FUNCTION%(%ARGS%) -> %RESULT% {
    execute_sync_function("%JS_FUNCTION%", %ARGS_INPUT%).unwrap_or_trap_result()
}`;

const templateAsyncQuery = `#[ic_cdk::query]
async fn %RS_FUNCTION%(%ARGS%) -> %RESULT% {
    execute_async_function::<%ARGS%, %RESULT%>("%JS_FUNCTION%", %ARGS_INPUT%)
        .await
        .unwrap_or_trap_result()
}`;

export const parseFunctions = ({queries, updates}: {queries: [string, Query][]; updates: [string, Update][]}): string => {



  return template;
};

const parseFunction = ({fn, output}: {fn: Query | Update, output: 'query' | 'update'}): string => {
  const args = 'args' in fn ? fn.args : undefined;
  const result = 'result' in fn ? fn.result : undefined;

  const isAsync = fn.handler instanceof Promise;

  const parse = (template: string): string => template

  if (isAsync) {
    if (output === 'query') {

    }


  }
};