import {nonNullish, notEmptyString} from '@dfinity/utils';
import type {Query, Update} from '@junobuild/functions';
import {zodToRust} from '@junobuild/zod';
import {capitalize, convertCamelToSnake} from '@junobuild/utils';
import {FUNCTION_NAMESPACE} from '../_constants';

const template = `// This file was automatically generated by the Juno CLI.
// Any modifications may be overwritten.
#![allow(unused)]
#![allow(non_camel_case_types)]

use crate::functions::{
    execute_async_function, execute_sync_function,
    types::{NoArgs, NoResult},
};
use candid::{CandidType, Principal};
use junobuild_macros::JsonData;
use junobuild_shared::ic::UnwrapOrTrap;
use junobuild_shared::ic::UnwrapOrTrapResult;
use serde::{Deserialize, Serialize};

%FUNCTIONS%
`;

const templateSyncNoArgsNoResult = `#[ic_cdk::%TYPE%]
fn %RS_FUNCTION%() {
    execute_sync_function::<NoArgs, NoResult>("%JS_FUNCTION%", None).unwrap_or_trap();
}`;

const templateSyncNoArgsWithResult = `#[ic_cdk::%TYPE%]
fn %RS_FUNCTION%() -> %RESULT% {
    execute_sync_function::<NoArgs, %RESULT%>("%JS_FUNCTION%", None).unwrap_or_trap_result()
}`;

const templateSyncWithArgsNoResult = `#[ic_cdk::%TYPE%]
fn %RS_FUNCTION%(args: %ARGS%) {
    execute_sync_function::<%ARGS%, NoResult>("%JS_FUNCTION%", Some(args)).unwrap_or_trap();
}`;

const templateSyncWithArgsWithResult = `#[ic_cdk::%TYPE%]
fn %RS_FUNCTION%(args: %ARGS%) -> %RESULT% {
    execute_sync_function("%JS_FUNCTION%", Some(args)).unwrap_or_trap_result()
}`;

const templateAsyncNoArgsNoResult = `#[ic_cdk::%TYPE%]
async fn %RS_FUNCTION%() {
    execute_async_function::<NoArgs, NoResult>("%JS_FUNCTION%", None)
        .await
        .unwrap_or_trap();
}`;

const templateAsyncNoArgsWithResult = `#[ic_cdk::%TYPE%]
async fn %RS_FUNCTION%() -> %RESULT% {
    execute_async_function::<NoArgs, %RESULT%>("%JS_FUNCTION%", None)
        .await
        .unwrap_or_trap_result()
}`;

const templateAsyncWithArgsNoResult = `#[ic_cdk::%TYPE%]
async fn %RS_FUNCTION%(args: %ARGS%) {
    execute_async_function::<%ARGS%, NoResult>("%JS_FUNCTION%", Some(args))
        .await
        .unwrap_or_trap();
}`;

const templateAsyncWithArgsWithResult = `#[ic_cdk::%TYPE%]
async fn %RS_FUNCTION%(args: %ARGS%) -> %RESULT% {
    execute_async_function("%JS_FUNCTION%", Some(args))
        .await
        .unwrap_or_trap_result()
}`;

export const parseFunctions = ({
  queries,
  updates
}: {
  queries: [string, Query][];
  updates: [string, Update][];
}): string => {
  const templateQueries = queries
    .map(([jsFnName, fn]) => parseFunction({jsFnName, fn, fnType: 'query'}))
    .join('\n\n');

  const templateUpdates = updates
    .map(([jsFnName, fn]) => parseFunction({jsFnName, fn, fnType: 'update'}))
    .join('\n\n');

  const functions = `${templateQueries}\n\n${templateUpdates}`.trim();

  return template.replace('%FUNCTIONS%', functions);
};

const parseFunction = ({
  fn,
  fnType,
  jsFnName
}: {
  fn: Query | Update;
  jsFnName: string;
  fnType: 'query' | 'update';
}): string => {
  const structName = `${FUNCTION_NAMESPACE}${capitalize(jsFnName)}`;

  const args =
    'args' in fn
      ? zodToRust({
          id: structName,
          schema: fn.args,
          suffix: 'Args'
        })
      : undefined;

  const result =
    'result' in fn
      ? zodToRust({
          id: structName,
          schema: fn.result,
          suffix: 'Result'
        })
      : undefined;

  const isAsync = fn.handler.constructor.name === 'AsyncFunction';

  const withTemplate = (): string => {
    if (nonNullish(args) && nonNullish(result)) {
      return isAsync ? templateAsyncWithArgsWithResult : templateSyncWithArgsWithResult;
    }
    if (nonNullish(args)) {
      return isAsync ? templateAsyncWithArgsNoResult : templateSyncWithArgsNoResult;
    }
    if (nonNullish(result)) {
      return isAsync ? templateAsyncNoArgsWithResult : templateSyncNoArgsWithResult;
    }
    return isAsync ? templateAsyncNoArgsNoResult : templateSyncNoArgsNoResult;
  };

  const template = withTemplate();

  const rsFnName = `${FUNCTION_NAMESPACE.toLowerCase()}_${convertCamelToSnake(jsFnName)}`;

  const parsedFn = template
    .replace('%TYPE%', fnType)
    .replace('%RS_FUNCTION%', rsFnName)
    .replace('%JS_FUNCTION%', jsFnName)
    .replaceAll('%ARGS%', args?.baseName ?? '') // We assume our templates and resolution is correct
    .replaceAll('%RESULT%', result?.baseName ?? '') // Ditto
    .trim();

  const parsedArgs = args?.code ?? '';
  const parsedResult = result?.code ?? '';

  return `${parsedArgs}${notEmptyString(parsedArgs) ? '\n\n' : ''}${parsedResult}${notEmptyString(parsedResult) ? '\n\n' : ''}${parsedFn}`;
};
