import {nonNullish} from '@dfinity/utils';
import type {Query, Update} from '@junobuild/functions';
import {zodToRust} from '../../zod';

const template = `// This file was automatically generated by the Juno CLI.
// Any modifications may be overwritten.
#![allow(unused)]

use crate::functions::{
    execute_async_function, execute_sync_function,
    types::{NoArgs, NoResult},
};
use candid::{CandidType, Principal};
use junobuild_macros::JsonData;
use junobuild_shared::ic::UnwrapOrTrap;
use junobuild_shared::ic::UnwrapOrTrapResult;
use serde::{Deserialize, Serialize};

%FUNCTIONS%
`;

const templateSyncNoArgsNoResult = `#[ic_cdk::%TYPE%]
fn %RS_FUNCTION%() {
    execute_sync_function::<NoArgs, NoResult>("%JS_FUNCTION%", None).unwrap_or_trap();
}`;

const templateSyncNoArgsWithResult = `#[ic_cdk::%TYPE%]
fn %RS_FUNCTION%() -> %RESULT% {
    execute_sync_function::<NoArgs, %RESULT%>("%JS_FUNCTION%", None).unwrap_or_trap_result()
}`;

const templateSyncWithArgsNoResult = `#[ic_cdk::%TYPE%]
fn %RS_FUNCTION%(args: %ARGS%) {
    execute_sync_function::<%ARGS%, NoResult>("%JS_FUNCTION%", Some(args)).unwrap_or_trap();
}`;

const templateSyncWithArgsWithResult = `#[ic_cdk::%TYPE%]
fn %RS_FUNCTION%(args: %ARGS%) -> %RESULT% {
    execute_sync_function("%JS_FUNCTION%", Some(args)).unwrap_or_trap_result()
}`;

const templateAsyncNoArgsNoResult = `#[ic_cdk::%TYPE%]
async fn %RS_FUNCTION%() {
    execute_async_function::<NoArgs, NoResult>("%JS_FUNCTION%", None)
        .await
        .unwrap_or_trap();
}`;

const templateAsyncNoArgsWithResult = `#[ic_cdk::%TYPE%]
async fn %RS_FUNCTION%() -> %RESULT% {
    execute_async_function::<NoArgs, %RESULT%>("%JS_FUNCTION%", None)
        .await
        .unwrap_or_trap_result()
}`;

const templateAsyncWithArgsNoResult = `#[ic_cdk::%TYPE%]
async fn %RS_FUNCTION%(args: %ARGS%) {
    execute_async_function::<%ARGS%, NoResult>("%JS_FUNCTION%", Some(args))
        .await
        .unwrap_or_trap();
}`;

const templateAsyncWithArgsWithResult = `#[ic_cdk::%TYPE%]
async fn %RS_FUNCTION%(args: %ARGS%) -> %RESULT% {
    execute_async_function("%JS_FUNCTION%", Some(args))
        .await
        .unwrap_or_trap_result()
}`;

export const parseFunctions = ({
  queries,
  updates
}: {
  queries: [string, Query][];
  updates: [string, Update][];
}): string => {
  const templateQueries = queries
    .map(([jsFnName, fn]) => parseFunction({jsFnName, fn, fnType: 'query'}))
    .join('\n\n');

  const templateUpdates = updates
    .map(([jsFnName, fn]) => parseFunction({jsFnName, fn, fnType: 'update'}))
    .join('\n\n');

  const functions = `${templateQueries}\n\n${templateUpdates}`.trim();

  return template.replace('%FUNCTIONS%', functions);
};

const parseFunction = ({
  fn,
  fnType,
  jsFnName
}: {
  fn: Query | Update;
  jsFnName: string;
  fnType: 'query' | 'update';
}): string => {
  const args =
    'args' in fn
      ? zodToRust({
          jsFnName: fn.args
        })
      : undefined;

  const result =
    'result' in fn
      ? zodToRust({
          jsFnName: fn.result
        })
      : undefined;

  const isAsync = fn.handler instanceof Promise;

  const withTemplate = (): string => {
    if (nonNullish(args) && nonNullish(result)) {
      return isAsync ? templateAsyncWithArgsWithResult : templateSyncWithArgsWithResult;
    } if (nonNullish(args)) {
      return isAsync ? templateAsyncWithArgsNoResult : templateSyncWithArgsNoResult;
    } if (nonNullish(result)) {
      return isAsync ? templateAsyncNoArgsWithResult : templateSyncNoArgsWithResult;
    } 
      return isAsync ? templateAsyncNoArgsNoResult : templateSyncNoArgsNoResult;
    
  };

  const template = withTemplate();

  const rsFnName = convertCamelToSnake(jsFnName);

  return template
    .replace('%TYPE%', fnType)
    .replace('%RS_FUNCTION%', rsFnName)
    .replace('%JS_FUNCTION%', jsFnName)
    .replaceAll('%ARGS%', args ?? '') // We assume our templates and resolution is correct
    .replaceAll('%RESULT%', args ?? '') // Ditto
    .trim();
};

// Source: https://stackoverflow.com/a/77489094/5404186
const convertCamelToSnake = (str: string): string => str.replace(/([a-zA-Z])(?=[A-Z])/g, '$1_').toLowerCase();
