import type {Query, Update} from '@junobuild/functions';
import {capitalize, convertCamelToSnake, nonNullish} from '@junobuild/utils';
import {BACKEND_FUNCTION_NAMESPACE, FRONTEND_FUNCTION_NAMESPACE} from '../../../constants';
import {zodToSchema} from '../../../converters/zod-to-schema';
import {templateNamespace} from '../../_contants';
import type {TransformerOptions} from '../../types/transformer-options';
import {
  jsTemplateImports,
  jsTemplateNoArgsNoResult,
  jsTemplateNoArgsWithResult,
  jsTemplateWithArgsNoResult,
  jsTemplateWithArgsWithResult
} from './_javascript.templates';
import {
  tsTemplateImports,
  tsTemplateNoArgsNoResult,
  tsTemplateNoArgsWithResult,
  tsTemplateWithArgsNoResult,
  tsTemplateWithArgsWithResult
} from './_typescript.templates';

const template = `// This file was automatically generated by the Juno CLI.
// Any modifications may be overwritten.

/* eslint-disable */
/* prettier-ignore */

%IMPORTS%

%FUNCTIONS%

%NAMESPACE%`;

export const parseSchemaApi = ({
  functions: devFunctions,
  transformerOptions: {coreLib, outputLanguage}
}: {
  functions: [string, Update | Query][];
  transformerOptions: TransformerOptions;
}): string => {
  const functions = devFunctions
    .map(([jsFnName, fn]) => parseApi({jsFnName, fn, outputLanguage}))
    .join('\n\n')
    .trim();

  const functionNames = devFunctions.map(([jsFnName, _]) => jsFnName).join(',\n\t');

  const namespaceExport = templateNamespace
    .replace('%FUNCTION_NAMESPACE%', FRONTEND_FUNCTION_NAMESPACE)
    .replace('%JS_FUNCTIONS%', functionNames);

  return template
    .replace('%IMPORTS%', outputLanguage === 'js' ? jsTemplateImports : tsTemplateImports)
    .replace('%CORE_LIB%', coreLib ?? 'core')
    .replace('%FUNCTIONS%', functions)
    .replace('%NAMESPACE%', namespaceExport);
};

const parseApi = ({
  fn,
  jsFnName,
  outputLanguage
}: {
  fn: Query | Update;
  jsFnName: string;
} & Pick<TransformerOptions, 'outputLanguage'>): string => {
  const structName = `${BACKEND_FUNCTION_NAMESPACE}${capitalize(jsFnName)}`;

  const args =
    'args' in fn
      ? zodToSchema({
          id: structName,
          schema: fn.args,
          suffix: 'Args'
        })
      : undefined;

  const result =
    'result' in fn
      ? zodToSchema({
          id: structName,
          schema: fn.result,
          suffix: 'Result'
        })
      : undefined;

  const withTemplate = (): string => {
    if (nonNullish(args) && nonNullish(result)) {
      return outputLanguage === 'js' ? jsTemplateWithArgsWithResult : tsTemplateWithArgsWithResult;
    }

    if (nonNullish(args)) {
      return outputLanguage === 'js' ? jsTemplateWithArgsNoResult : tsTemplateWithArgsNoResult;
    }

    if (nonNullish(result)) {
      return outputLanguage === 'js' ? jsTemplateNoArgsWithResult : tsTemplateNoArgsWithResult;
    }

    return outputLanguage === 'js' ? jsTemplateNoArgsNoResult : tsTemplateNoArgsNoResult;
  };

  const template = withTemplate();

  const rsFnName = `${BACKEND_FUNCTION_NAMESPACE.toLowerCase()}_${convertCamelToSnake(jsFnName)}`;

  return template
    .replace('%JS_FUNCTION%', jsFnName)
    .replaceAll('%RS_FUNCTION%', rsFnName)
    .replaceAll('%ARGS_SCHEMA%', args?.baseName ? `${args.baseName}Schema` : '')
    .replaceAll('%ARGS_ZOD%', args?.code ?? '')
    .replaceAll('%RESULT_SCHEMA%', result?.baseName ? `${result.baseName}Schema` : '')
    .replaceAll('%RESULT_ZOD%', result?.code ?? '')
    .trim();
};
