import type {Query, Update} from '@junobuild/functions';
import {capitalize, convertCamelToSnake, nonNullish} from '@junobuild/utils';
import {BACKEND_FUNCTION_NAMESPACE} from '../../constants';
import {zodToCandid} from '../../converters';

const template = `// This file was automatically generated by the Juno CLI.
// Any modifications may be overwritten.

%TYPES%service : {
\t%METHODS%
};`;

export const parseDidApi = ({
  queries,
  updates
}: {
  updates: [string, Update][];
  queries: [string, Query][];
}): string => {
  const templateQueries = queries.map(([jsFnName, fn]) =>
    parseDid({jsFnName, fn, fnType: 'query'})
  );

  const templateUpdates = updates.map(([jsFnName, fn]) =>
    parseDid({jsFnName, fn, fnType: 'update'})
  );

  const [types, methods] = [...templateQueries, ...templateUpdates].reduce<[string[], string[]]>(
    ([types, methods], {types: fnTypes, method}) => [
      [...types, ...fnTypes],
      [...methods, method]
    ],
    [[], []]
  );

  return template
    .replace('%TYPES%', types.length > 0 ? `${types.join('\n\n')}\n\n` : '')
    .replace('%METHODS%', methods.join('\n').trim())
    .trim();
};

interface ParsedCandid {
  types: string[];
  method: string;
}

const parseDid = ({
  fn,
  jsFnName,
  fnType
}: {
  fn: Query | Update;
  fnType: 'query' | 'update';
  jsFnName: string;
}): ParsedCandid => {
  const structName = `${BACKEND_FUNCTION_NAMESPACE}${capitalize(jsFnName)}`;

  const args =
    'args' in fn
      ? zodToCandid({
          id: structName,
          schema: fn.args,
          suffix: 'Args'
        })
      : undefined;

  const result =
    'result' in fn
      ? zodToCandid({
          id: structName,
          schema: fn.result,
          suffix: 'Result'
        })
      : undefined;

  const types = [
    ...(nonNullish(args) ? [args.code] : []),
    ...(nonNullish(result) ? [result.code] : [])
  ];

  const querySuffix = fnType === 'query' ? ' query' : '';

  const methodArgs = nonNullish(args) ? `(${args.baseName})` : '()';
  const methodResult = nonNullish(result) ? `(${result.baseName})` : '()';

  const rsFnName = `${BACKEND_FUNCTION_NAMESPACE.toLowerCase()}_${convertCamelToSnake(jsFnName)}`;

  const method = `\t${rsFnName} : ${methodArgs} -> ${methodResult}${querySuffix};`;

  return {types, method};
};
