import {parseDidApi} from '../../../did/services/parser.services';
import {
  mockQueryNoArgsNoResult,
  mockQueryNoArgsWithResult,
  mockQueryWithArgsNoResult,
  mockQueryWithArgsWithResult,
  mockQueryWithArray,
  mockQueryWithEnum,
  mockQueryWithNestedObject,
  mockQueryWithPrincipal,
  mockQueryWithUint8Array
} from '../../mocks/zod-functions.mock';

describe('did-api-parser', () => {
  // ─── file header ─────────────────────────────────────────────────────────────

  describe('file header', () => {
    it('should include generated comment', () => {
      const result = parseDidApi({
        queries: [['helloWorld', mockQueryNoArgsNoResult]],
        updates: []
      });
      expect(result).toContain('// This file was automatically generated by the Juno CLI.');
      expect(result).toContain('// Any modifications may be overwritten.');
    });
  });

  // ─── service block ───────────────────────────────────────────────────────────

  describe('service block', () => {
    it('should include service declaration', () => {
      const result = parseDidApi({
        queries: [['helloWorld', mockQueryNoArgsNoResult]],
        updates: []
      });
      expect(result).toContain('service : {');
      expect(result).toContain('};');
    });
  });

  // ─── no args no result ───────────────────────────────────────────────────────

  describe('no args no result', () => {
    it('should generate method with empty args and empty result', () => {
      const result = parseDidApi({
        queries: [['helloWorld', mockQueryNoArgsNoResult]],
        updates: []
      });
      expect(result).toContain('app_hello_world : () -> () query;');
      expect(result).not.toContain('AppHelloWorldArgs');
      expect(result).not.toContain('AppHelloWorldResult');
    });
  });

  // ─── args only ───────────────────────────────────────────────────────────────

  describe('args only', () => {
    it('should generate type and method with args', () => {
      const result = parseDidApi({
        queries: [['helloWorld', mockQueryWithArgsNoResult]],
        updates: []
      });
      expect(result).toContain('type AppHelloWorldArgs = record { name : text };');
      expect(result).toContain('app_hello_world : (AppHelloWorldArgs) -> () query;');
      expect(result).not.toContain('AppHelloWorldResult');
    });
  });

  // ─── result only ─────────────────────────────────────────────────────────────

  describe('result only', () => {
    it('should generate type and method with result', () => {
      const result = parseDidApi({
        queries: [['helloWorld', mockQueryNoArgsWithResult]],
        updates: []
      });
      expect(result).toContain('type AppHelloWorldResult = record { value : text };');
      expect(result).toContain('app_hello_world : () -> (AppHelloWorldResult) query;');
      expect(result).not.toContain('AppHelloWorldArgs');
    });
  });

  // ─── args and result ─────────────────────────────────────────────────────────

  describe('args and result', () => {
    it('should generate both types and method', () => {
      const result = parseDidApi({
        queries: [['helloWorld', mockQueryWithArgsWithResult]],
        updates: []
      });
      expect(result).toContain('type AppHelloWorldArgs = record { name : text; age : opt int32 };');
      expect(result).toContain(
        'type AppHelloWorldResult = record { value : text; count : nat64 };'
      );
      expect(result).toContain(
        'app_hello_world : (AppHelloWorldArgs) -> (AppHelloWorldResult) query;'
      );
    });
  });

  // ─── query suffix ────────────────────────────────────────────────────────────

  describe('query suffix', () => {
    it('should append query suffix for queries', () => {
      const result = parseDidApi({
        queries: [['helloWorld', mockQueryWithArgsWithResult]],
        updates: []
      });
      expect(result).toContain(
        'app_hello_world : (AppHelloWorldArgs) -> (AppHelloWorldResult) query;'
      );
    });

    it('should not append query suffix for updates', () => {
      const result = parseDidApi({
        queries: [],
        updates: [['helloWorld', mockQueryWithArgsWithResult]]
      });
      expect(result).not.toContain('query;');
    });
  });

  // ─── rs function name ────────────────────────────────────────────────────────

  describe('rs function name', () => {
    it('should convert camelCase to snake_case with namespace prefix', () => {
      const result = parseDidApi({
        queries: [['helloWorld', mockQueryNoArgsNoResult]],
        updates: []
      });
      expect(result).toContain('app_hello_world');
    });

    it('should handle single word function name', () => {
      const result = parseDidApi({
        queries: [['greet', mockQueryNoArgsNoResult]],
        updates: []
      });
      expect(result).toContain('app_greet');
    });

    it('should handle long camelCase function name', () => {
      const result = parseDidApi({
        queries: [['getSatelliteConfig', mockQueryNoArgsNoResult]],
        updates: []
      });
      expect(result).toContain('app_get_satellite_config');
    });
  });

  // ─── type naming ─────────────────────────────────────────────────────────────

  describe('type naming', () => {
    it('should prefix type with BACKEND_FUNCTION_NAMESPACE and capitalize', () => {
      const result = parseDidApi({
        queries: [['helloWorld', mockQueryWithArgsWithResult]],
        updates: []
      });
      expect(result).toContain('AppHelloWorldArgs');
      expect(result).toContain('AppHelloWorldResult');
    });

    it('should handle single word function name in type', () => {
      const result = parseDidApi({
        queries: [['greet', mockQueryWithArgsWithResult]],
        updates: []
      });
      expect(result).toContain('AppGreetArgs');
      expect(result).toContain('AppGreetResult');
    });
  });

  // ─── queries vs updates ──────────────────────────────────────────────────────

  describe('queries vs updates', () => {
    it('should generate methods for queries', () => {
      const result = parseDidApi({
        queries: [['helloWorld', mockQueryNoArgsNoResult]],
        updates: []
      });
      expect(result).toContain('app_hello_world');
    });

    it('should generate methods for updates', () => {
      const result = parseDidApi({
        queries: [],
        updates: [['helloWorld', mockQueryNoArgsNoResult]]
      });
      expect(result).toContain('app_hello_world');
    });

    it('should generate methods for both queries and updates', () => {
      const result = parseDidApi({
        queries: [['getUser', mockQueryNoArgsWithResult]],
        updates: [['setUser', mockQueryWithArgsNoResult]]
      });
      expect(result).toContain('app_get_user');
      expect(result).toContain('app_set_user');
    });

    it('should handle empty queries and updates', () => {
      const result = parseDidApi({queries: [], updates: []});
      expect(result).toContain('// This file was automatically generated');
      expect(result).toContain('service : {');
    });
  });

  // ─── multiple functions ──────────────────────────────────────────────────────

  describe('multiple functions', () => {
    it('should generate multiple methods', () => {
      const result = parseDidApi({
        queries: [
          ['getUser', mockQueryNoArgsWithResult],
          ['listUsers', mockQueryNoArgsWithResult]
        ],
        updates: [['setUser', mockQueryWithArgsNoResult]]
      });
      expect(result).toContain('app_get_user');
      expect(result).toContain('app_list_users');
      expect(result).toContain('app_set_user');
    });

    it('should generate types for all functions with args or result', () => {
      const result = parseDidApi({
        queries: [['getUser', mockQueryNoArgsWithResult]],
        updates: [['setUser', mockQueryWithArgsNoResult]]
      });
      expect(result).toContain('type AppGetUserResult');
      expect(result).toContain('type AppSetUserArgs');
    });
  });

  // ─── schema types ────────────────────────────────────────────────────────────

  describe('schema types', () => {
    it('should handle principal in args', () => {
      const result = parseDidApi({
        queries: [['helloWorld', mockQueryWithPrincipal]],
        updates: []
      });
      expect(result).toContain('principal');
    });

    it('should handle Uint8Array in args', () => {
      const result = parseDidApi({
        queries: [['helloWorld', mockQueryWithUint8Array]],
        updates: []
      });
      expect(result).toContain('blob');
    });

    it('should handle array fields', () => {
      const result = parseDidApi({
        queries: [['helloWorld', mockQueryWithArray]],
        updates: []
      });
      expect(result).toContain('vec text');
    });

    it('should handle enum fields', () => {
      const result = parseDidApi({
        queries: [['helloWorld', mockQueryWithEnum]],
        updates: []
      });
      expect(result).toContain('variant { active; inactive }');
    });

    it('should handle nested objects', () => {
      const result = parseDidApi({
        queries: [['helloWorld', mockQueryWithNestedObject]],
        updates: []
      });
      expect(result).toContain('record { street : text; city : opt text }');
    });
  });

  // ─── full output ─────────────────────────────────────────────────────────────

  describe('full output', () => {
    it('should match no args no result', () => {
      const result = parseDidApi({
        queries: [['helloWorld', mockQueryNoArgsNoResult]],
        updates: []
      });
      expect(result.trim()).toEqual(
        `// This file was automatically generated by the Juno CLI.
// Any modifications may be overwritten.

service : {
\tapp_hello_world : () -> () query;
};`
      );
    });

    it('should match with args and result', () => {
      const result = parseDidApi({
        queries: [['helloWorld', mockQueryWithArgsWithResult]],
        updates: []
      });
      expect(result.trim()).toEqual(
        `// This file was automatically generated by the Juno CLI.
// Any modifications may be overwritten.

type AppHelloWorldArgs = record { name : text; age : opt int32 };

type AppHelloWorldResult = record { value : text; count : nat64 };

service : {
\tapp_hello_world : (AppHelloWorldArgs) -> (AppHelloWorldResult) query;
};`
      );
    });

    it('should match update with args and result', () => {
      const result = parseDidApi({
        queries: [],
        updates: [['helloWorld', mockQueryWithArgsWithResult]]
      });
      expect(result.trim()).toEqual(
        `// This file was automatically generated by the Juno CLI.
// Any modifications may be overwritten.

type AppHelloWorldArgs = record { name : text; age : opt int32 };

type AppHelloWorldResult = record { value : text; count : nat64 };

service : {
\tapp_hello_world : (AppHelloWorldArgs) -> (AppHelloWorldResult);
};`
      );
    });
  });
});
