import {parseSchemaApi} from '../../../../api/schema/services/parser.services';
import {
  mockQueryNoArgsNoResult,
  mockQueryNoArgsWithResult,
  mockQueryWithArgsNoResult,
  mockQueryWithArgsWithResult,
  mockQueryWithArray,
  mockQueryWithEnum,
  mockQueryWithNestedObject,
  mockQueryWithPrincipal,
  mockQueryWithUint8Array
} from '../../../mocks/zod-functions.mock';
import {
  mockJsFullNoArgsNoResult,
  mockJsNoArgsNoResult,
  mockJsNoArgsWithResult,
  mockJsWithArgsNoResult,
  mockJsWithArgsWithResult,
  mockTsFullNoArgsNoResult,
  mockTsNoArgsNoResult,
  mockTsNoArgsWithResult,
  mockTsWithArgsNoResult,
  mockTsWithArgsWithResult
} from '../mocks/zod-api-transformed.mock';

describe('parser.services', () => {
  // ─── file header ────────────────────────────────────────────────────────────

  describe('file header', () => {
    it('should include generated comment', () => {
      const result = parseSchemaApi({
        functions: [['helloWorld', mockQueryNoArgsNoResult]],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain('// This file was automatically generated by the Juno CLI.');
      expect(result).toContain('// Any modifications may be overwritten.');
    });

    it('should include eslint-disable comment', () => {
      const result = parseSchemaApi({
        functions: [['helloWorld', mockQueryNoArgsNoResult]],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain('/* eslint-disable */');
    });

    it('should include prettier-ignore comment', () => {
      const result = parseSchemaApi({
        functions: [['helloWorld', mockQueryNoArgsNoResult]],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain('/* prettier-ignore */');
    });

    it('should import SatelliteActor from satellite.did for ts', () => {
      const result = parseSchemaApi({
        functions: [['helloWorld', mockQueryNoArgsNoResult]],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain("import type {_SERVICE as SatelliteActor} from './satellite.did';");
    });

    it('should not import SatelliteActor for js', () => {
      const result = parseSchemaApi({
        functions: [['helloWorld', mockQueryNoArgsNoResult]],
        transformerOptions: {outputLanguage: 'js'}
      });
      expect(result).not.toContain('import type {_SERVICE as SatelliteActor}');
    });

    it('should import j from @junobuild/schema for ts', () => {
      const result = parseSchemaApi({
        functions: [['helloWorld', mockQueryNoArgsNoResult]],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain("import {j} from '@junobuild/schema';");
    });

    it('should import j from @junobuild/schema for js', () => {
      const result = parseSchemaApi({
        functions: [['helloWorld', mockQueryNoArgsNoResult]],
        transformerOptions: {outputLanguage: 'js'}
      });
      expect(result).toContain("import {j} from '@junobuild/schema';");
    });

    it('should import schemaToIdl and schemaFromIdl', () => {
      const result = parseSchemaApi({
        functions: [['helloWorld', mockQueryWithArgsWithResult]],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain(
        "import {schemaToIdl, schemaFromIdl} from '@junobuild/schema/utils';"
      );
    });

    it('should import from core by default', () => {
      const result = parseSchemaApi({
        functions: [['helloWorld', mockQueryNoArgsNoResult]],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain("import {getSatelliteExtendedActor} from '@junobuild/core';");
    });

    it('should import from core-standalone when specified', () => {
      const result = parseSchemaApi({
        functions: [['helloWorld', mockQueryNoArgsNoResult]],
        transformerOptions: {outputLanguage: 'ts', coreLib: 'core-standalone'}
      });
      expect(result).toContain(
        "import {getSatelliteExtendedActor} from '@junobuild/core-standalone';"
      );
    });

    it('should import idlFactory from satellite.factory.did.js for ts', () => {
      const result = parseSchemaApi({
        functions: [['helloWorld', mockQueryNoArgsNoResult]],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain("import {idlFactory} from './satellite.factory.did.js';");
    });

    it('should import idlFactory from satellite.factory.did.js for js', () => {
      const result = parseSchemaApi({
        functions: [['helloWorld', mockQueryNoArgsNoResult]],
        transformerOptions: {outputLanguage: 'js'}
      });
      expect(result).toContain("import {idlFactory} from './satellite.factory.did.js';");
    });
  });

  // ─── no args no result ───────────────────────────────────────────────────────

  describe('no args no result', () => {
    it('should generate ts function with no args and no result', () => {
      const result = parseSchemaApi({
        functions: [['helloWorld', mockQueryNoArgsNoResult]],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain('const helloWorld = async (): Promise<void>');
      expect(result).toContain('await app_hello_world();');
      expect(result).not.toContain('AppHelloWorldArgsSchema');
      expect(result).not.toContain('AppHelloWorldResultSchema');
    });

    it('should generate js function with no args and no result', () => {
      const result = parseSchemaApi({
        functions: [['helloWorld', mockQueryNoArgsNoResult]],
        transformerOptions: {outputLanguage: 'js'}
      });
      expect(result).toContain('const helloWorld = async ()');
      expect(result).not.toContain(': Promise<void>');
      expect(result).toContain('await app_hello_world();');
    });
  });

  // ─── args only ───────────────────────────────────────────────────────────────

  describe('args only', () => {
    it('should generate ts function with args and no result', () => {
      const result = parseSchemaApi({
        functions: [['helloWorld', mockQueryWithArgsNoResult]],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain(
        'const AppHelloWorldArgsSchema = j.strictObject({name: j.string()});'
      );
      expect(result).toContain('args: j.infer<typeof AppHelloWorldArgsSchema>');
      expect(result).toContain(': Promise<void>');
      expect(result).toContain('schemaToIdl({schema: AppHelloWorldArgsSchema, value: parsedArgs})');
      expect(result).not.toContain('AppHelloWorldResultSchema');
    });

    it('should generate js function with args and no result', () => {
      const result = parseSchemaApi({
        functions: [['helloWorld', mockQueryWithArgsNoResult]],
        transformerOptions: {outputLanguage: 'js'}
      });
      expect(result).toContain(
        'const AppHelloWorldArgsSchema = j.strictObject({name: j.string()});'
      );
      expect(result).toContain('const helloWorld = async (args)');
      expect(result).not.toContain(': Promise<void>');
      expect(result).not.toContain('AppHelloWorldResultSchema');
    });
  });

  // ─── result only ─────────────────────────────────────────────────────────────

  describe('result only', () => {
    it('should generate ts function with no args and result', () => {
      const result = parseSchemaApi({
        functions: [['helloWorld', mockQueryNoArgsWithResult]],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain(
        'const AppHelloWorldResultSchema = j.strictObject({value: j.string()});'
      );
      expect(result).toContain('Promise<j.infer<typeof AppHelloWorldResultSchema>>');
      expect(result).toContain(
        'schemaFromIdl({schema: AppHelloWorldResultSchema, value: idlResult})'
      );
      expect(result).toContain('return AppHelloWorldResultSchema.parse(result);');
      expect(result).not.toContain('AppHelloWorldArgsSchema');
    });

    it('should generate js function with no args and result', () => {
      const result = parseSchemaApi({
        functions: [['helloWorld', mockQueryNoArgsWithResult]],
        transformerOptions: {outputLanguage: 'js'}
      });
      expect(result).toContain(
        'const AppHelloWorldResultSchema = j.strictObject({value: j.string()});'
      );
      expect(result).toContain('const helloWorld = async ()');
      expect(result).not.toContain('Promise<');
      expect(result).not.toContain('AppHelloWorldArgsSchema');
    });
  });

  // ─── args and result ─────────────────────────────────────────────────────────

  describe('args and result', () => {
    it('should generate ts function with args and result', () => {
      const result = parseSchemaApi({
        functions: [['helloWorld', mockQueryWithArgsWithResult]],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain(
        'const AppHelloWorldArgsSchema = j.strictObject({name: j.string(), age: j.optional(j.int())});'
      );
      expect(result).toContain(
        'const AppHelloWorldResultSchema = j.strictObject({value: j.string(), count: j.bigint()});'
      );
      expect(result).toContain('args: j.infer<typeof AppHelloWorldArgsSchema>');
      expect(result).toContain('Promise<j.infer<typeof AppHelloWorldResultSchema>>');
      expect(result).toContain('schemaToIdl({schema: AppHelloWorldArgsSchema, value: parsedArgs})');
      expect(result).toContain(
        'schemaFromIdl({schema: AppHelloWorldResultSchema, value: idlResult})'
      );
      expect(result).toContain('return AppHelloWorldResultSchema.parse(result);');
    });

    it('should generate js function with args and result', () => {
      const result = parseSchemaApi({
        functions: [['helloWorld', mockQueryWithArgsWithResult]],
        transformerOptions: {outputLanguage: 'js'}
      });
      expect(result).toContain('const AppHelloWorldArgsSchema');
      expect(result).toContain('const AppHelloWorldResultSchema');
      expect(result).toContain('const helloWorld = async (args)');
      expect(result).not.toContain(': Promise<');
      expect(result).not.toContain('j.infer<');
    });
  });

  // ─── namespace export ────────────────────────────────────────────────────────

  describe('namespace export', () => {
    it('should export functions namespace for ts', () => {
      const result = parseSchemaApi({
        functions: [['helloWorld', mockQueryNoArgsNoResult]],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain('export const functions = {');
      expect(result).toContain('helloWorld');
    });

    it('should export functions namespace for js', () => {
      const result = parseSchemaApi({
        functions: [['helloWorld', mockQueryNoArgsNoResult]],
        transformerOptions: {outputLanguage: 'js'}
      });
      expect(result).toContain('export const functions = {');
      expect(result).toContain('helloWorld');
    });

    it('should include multiple functions in namespace', () => {
      const result = parseSchemaApi({
        functions: [
          ['getUser', mockQueryNoArgsWithResult],
          ['setUser', mockQueryWithArgsNoResult],
          ['deleteUser', mockQueryWithArgsNoResult]
        ],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain('export const functions = {');
      expect(result).toContain('getUser');
      expect(result).toContain('setUser');
      expect(result).toContain('deleteUser');
    });

    it('should not include namespace if no functions', () => {
      const result = parseSchemaApi({
        functions: [],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).not.toContain('export const functions = {');
    });
  });

  // ─── rs function name ────────────────────────────────────────────────────────

  describe('rs function name', () => {
    it('should convert camelCase to snake_case with namespace prefix', () => {
      const result = parseSchemaApi({
        functions: [['helloWorld', mockQueryNoArgsNoResult]],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain('app_hello_world');
    });

    it('should handle single word function name', () => {
      const result = parseSchemaApi({
        functions: [['greet', mockQueryNoArgsNoResult]],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain('app_greet');
    });

    it('should handle long camelCase function name', () => {
      const result = parseSchemaApi({
        functions: [['getSatelliteConfig', mockQueryNoArgsNoResult]],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain('app_get_satellite_config');
    });
  });

  // ─── schema naming ───────────────────────────────────────────────────────────

  describe('schema naming', () => {
    it('should prefix schema with FUNCTION_NAMESPACE and capitalize', () => {
      const result = parseSchemaApi({
        functions: [['helloWorld', mockQueryWithArgsWithResult]],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain('AppHelloWorldArgsSchema');
      expect(result).toContain('AppHelloWorldResultSchema');
    });

    it('should handle single word function name in schema', () => {
      const result = parseSchemaApi({
        functions: [['greet', mockQueryWithArgsWithResult]],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain('AppGreetArgsSchema');
      expect(result).toContain('AppGreetResultSchema');
    });
  });

  // ─── multiple functions ──────────────────────────────────────────────────────

  describe('multiple functions', () => {
    it('should generate multiple functions', () => {
      const result = parseSchemaApi({
        functions: [
          ['getUser', mockQueryNoArgsWithResult],
          ['listUsers', mockQueryNoArgsWithResult],
          ['searchUsers', mockQueryWithArgsWithResult]
        ],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain('const getUser');
      expect(result).toContain('const listUsers');
      expect(result).toContain('const searchUsers');
    });

    it('should handle empty functions', () => {
      const result = parseSchemaApi({
        functions: [],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain('// This file was automatically generated');
      expect(result).not.toContain('const helloWorld');
    });
  });

  // ─── schema types ────────────────────────────────────────────────────────────

  describe('schema types', () => {
    it('should handle principal in args', () => {
      const result = parseSchemaApi({
        functions: [['helloWorld', mockQueryWithPrincipal]],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain('j.principal()');
    });

    it('should handle Uint8Array in args', () => {
      const result = parseSchemaApi({
        functions: [['helloWorld', mockQueryWithUint8Array]],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain('j.uint8Array()');
    });

    it('should handle array fields', () => {
      const result = parseSchemaApi({
        functions: [['helloWorld', mockQueryWithArray]],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain('j.array(j.string())');
    });

    it('should handle enum fields', () => {
      const result = parseSchemaApi({
        functions: [['helloWorld', mockQueryWithEnum]],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain("j.enum(['active', 'inactive'])");
    });

    it('should handle nested objects', () => {
      const result = parseSchemaApi({
        functions: [['helloWorld', mockQueryWithNestedObject]],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result).toContain(
        'j.strictObject({street: j.string(), city: j.optional(j.string())})'
      );
    });
  });

  // ─── full output ─────────────────────────────────────────────────────────────

  describe('full output', () => {
    it('should match ts no args no result', () => {
      const result = parseSchemaApi({
        functions: [['helloWorld', mockQueryNoArgsNoResult]],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result.trim()).toContain(mockTsNoArgsNoResult);
    });

    it('should match ts with args no result', () => {
      const result = parseSchemaApi({
        functions: [['helloWorld', mockQueryWithArgsNoResult]],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result.trim()).toContain(mockTsWithArgsNoResult);
    });

    it('should match ts no args with result', () => {
      const result = parseSchemaApi({
        functions: [['helloWorld', mockQueryNoArgsWithResult]],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result.trim()).toContain(mockTsNoArgsWithResult);
    });

    it('should match ts with args and result', () => {
      const result = parseSchemaApi({
        functions: [['helloWorld', mockQueryWithArgsWithResult]],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result.trim()).toContain(mockTsWithArgsWithResult);
    });

    it('should match js no args no result', () => {
      const result = parseSchemaApi({
        functions: [['helloWorld', mockQueryNoArgsNoResult]],
        transformerOptions: {outputLanguage: 'js'}
      });
      expect(result.trim()).toContain(mockJsNoArgsNoResult);
    });

    it('should match js with args no result', () => {
      const result = parseSchemaApi({
        functions: [['helloWorld', mockQueryWithArgsNoResult]],
        transformerOptions: {outputLanguage: 'js'}
      });
      expect(result.trim()).toContain(mockJsWithArgsNoResult);
    });

    it('should match js no args with result', () => {
      const result = parseSchemaApi({
        functions: [['helloWorld', mockQueryNoArgsWithResult]],
        transformerOptions: {outputLanguage: 'js'}
      });
      expect(result.trim()).toContain(mockJsNoArgsWithResult);
    });

    it('should match js with args and result', () => {
      const result = parseSchemaApi({
        functions: [['helloWorld', mockQueryWithArgsWithResult]],
        transformerOptions: {outputLanguage: 'js'}
      });
      expect(result.trim()).toContain(mockJsWithArgsWithResult);
    });

    it('should match full ts output no args no result', () => {
      const result = parseSchemaApi({
        functions: [['helloWorld', mockQueryNoArgsNoResult]],
        transformerOptions: {outputLanguage: 'ts'}
      });
      expect(result.trim()).toEqual(mockTsFullNoArgsNoResult);
    });

    it('should match full js output no args no result', () => {
      const result = parseSchemaApi({
        functions: [['helloWorld', mockQueryNoArgsNoResult]],
        transformerOptions: {outputLanguage: 'js'}
      });
      expect(result.trim()).toEqual(mockJsFullNoArgsNoResult);
    });
  });
});
