export const mockTsNoArgsNoResult = `const helloWorld = async (): Promise<void> => {
\tconst {app_hello_world} = await getSatelliteExtendedActor<SatelliteActor>({idlFactory});
\tawait app_hello_world();
};`;

export const mockTsWithArgsNoResult = `const AppHelloWorldArgsSchema = j.strictObject({name: j.string()});

const helloWorld = async (args: j.infer<typeof AppHelloWorldArgsSchema>): Promise<void> => {
\tconst parsedArgs = AppHelloWorldArgsSchema.parse(args);
\tconst idlArgs = schemaToIdl({schema: AppHelloWorldArgsSchema, value: parsedArgs}) as Parameters<SatelliteActor['app_hello_world']>[0];

\tconst {app_hello_world} = await getSatelliteExtendedActor<SatelliteActor>({idlFactory});
\tawait app_hello_world(idlArgs);
};`;

export const mockTsNoArgsWithResult = `const AppHelloWorldResultSchema = j.strictObject({value: j.string()});

const helloWorld = async (): Promise<j.infer<typeof AppHelloWorldResultSchema>> => {
\tconst {app_hello_world} = await getSatelliteExtendedActor<SatelliteActor>({idlFactory});
\tconst idlResult = await app_hello_world();

\tconst result = schemaFromIdl({schema: AppHelloWorldResultSchema, value: idlResult});
\treturn AppHelloWorldResultSchema.parse(result);
};`;

export const mockTsWithArgsWithResult = `const AppHelloWorldArgsSchema = j.strictObject({name: j.string(), age: j.optional(j.int())});
const AppHelloWorldResultSchema = j.strictObject({value: j.string(), count: j.bigint()});

const helloWorld = async (args: j.infer<typeof AppHelloWorldArgsSchema>): Promise<j.infer<typeof AppHelloWorldResultSchema>> => {
\tconst parsedArgs = AppHelloWorldArgsSchema.parse(args);
\tconst idlArgs = schemaToIdl({schema: AppHelloWorldArgsSchema, value: parsedArgs}) as Parameters<SatelliteActor['app_hello_world']>[0];

\tconst {app_hello_world} = await getSatelliteExtendedActor<SatelliteActor>({idlFactory});
\tconst idlResult = await app_hello_world(idlArgs);

\tconst result = schemaFromIdl({schema: AppHelloWorldResultSchema, value: idlResult});
\treturn AppHelloWorldResultSchema.parse(result);
};`;

export const mockJsNoArgsNoResult = `const helloWorld = async () => {
\tconst {app_hello_world} = await getSatelliteExtendedActor({idlFactory});
\tawait app_hello_world();
};`;

export const mockJsWithArgsNoResult = `const AppHelloWorldArgsSchema = j.strictObject({name: j.string()});

const helloWorld = async (args) => {
\tconst parsedArgs = AppHelloWorldArgsSchema.parse(args);
\tconst idlArgs = schemaToIdl({schema: AppHelloWorldArgsSchema, value: parsedArgs});

\tconst {app_hello_world} = await getSatelliteExtendedActor({idlFactory});
\tawait app_hello_world(idlArgs);
};`;

export const mockJsNoArgsWithResult = `const AppHelloWorldResultSchema = j.strictObject({value: j.string()});

const helloWorld = async () => {
\tconst {app_hello_world} = await getSatelliteExtendedActor({idlFactory});
\tconst idlResult = await app_hello_world();

\tconst result = schemaFromIdl({schema: AppHelloWorldResultSchema, value: idlResult});
\treturn AppHelloWorldResultSchema.parse(result);
};`;

export const mockJsWithArgsWithResult = `const AppHelloWorldArgsSchema = j.strictObject({name: j.string(), age: j.optional(j.int())});
const AppHelloWorldResultSchema = j.strictObject({value: j.string(), count: j.bigint()});

const helloWorld = async (args) => {
\tconst parsedArgs = AppHelloWorldArgsSchema.parse(args);
\tconst idlArgs = schemaToIdl({schema: AppHelloWorldArgsSchema, value: parsedArgs});

\tconst {app_hello_world} = await getSatelliteExtendedActor({idlFactory});
\tconst idlResult = await app_hello_world(idlArgs);

\tconst result = schemaFromIdl({schema: AppHelloWorldResultSchema, value: idlResult});
\treturn AppHelloWorldResultSchema.parse(result);
};`;

export const mockTsFullNoArgsNoResult = `// This file was automatically generated by the Juno CLI.
// Any modifications may be overwritten.

/* eslint-disable */
/* prettier-ignore */

import type {_SERVICE as SatelliteActor} from './satellite.did';
// @ts-expect-error - generated JS file without type declarations
import {idlFactory} from './satellite.factory.did.js';
import {getSatelliteExtendedActor} from '@junobuild/core';
import {schemaToIdl, schemaFromIdl} from '@junobuild/schema/utils';
import {j} from '@junobuild/schema';

const helloWorld = async (): Promise<void> => {
\tconst {app_hello_world} = await getSatelliteExtendedActor<SatelliteActor>({idlFactory});
\tawait app_hello_world();
};

export const functions = {
\thelloWorld
};`;

export const mockJsFullNoArgsNoResult = `// This file was automatically generated by the Juno CLI.
// Any modifications may be overwritten.

/* eslint-disable */
/* prettier-ignore */

// @ts-expect-error - generated JS file without type declarations
import {idlFactory} from './satellite.factory.did.js';
import {getSatelliteExtendedActor} from '@junobuild/core';
import {schemaToIdl, schemaFromIdl} from '@junobuild/schema/utils';
import {j} from '@junobuild/schema';

const helloWorld = async () => {
\tconst {app_hello_world} = await getSatelliteExtendedActor({idlFactory});
\tawait app_hello_world();
};

export const functions = {
\thelloWorld
};`;
