import {j} from '@junobuild/schema';
import * as z from 'zod';
import {parseFunctions} from '../../../functions/services/parser.services';

const DERIVES = '#[derive(CandidType, Serialize, Deserialize, Clone, JsonData)]';

describe('parseFunctions', () => {
  it('should include the header', () => {
    const result = parseFunctions({
      queries: [['helloWorld', {handler: () => {}}]],
      updates: []
    });

    expect(result).toContain(`// This file was automatically generated by the Juno CLI.
// Any modifications may be overwritten.
#![allow(unused)]
#![allow(non_camel_case_types)]

use crate::functions::{
    execute_async_function, execute_guard, execute_sync_function,
    types::{NoArgs, NoResult},
};
use candid::{CandidType, Principal};
use junobuild_macros::JsonData;
use junobuild_shared::ic::UnwrapOrTrap;
use junobuild_shared::ic::UnwrapOrTrapResult;
use serde::{Deserialize, Serialize};`);
  });


  describe('query', () => {
    it('should generate a sync query with no args and no result', () => {
      const result = parseFunctions({
        queries: [['helloWorld', {handler: () => {}}]],
        updates: []
      });

      expect(result).toContain('#[ic_cdk::query]');
      expect(result).toContain('fn app_hello_world()');
      expect(result).toContain(
        'execute_sync_function::<NoArgs, NoResult>("helloWorld", None).unwrap_or_trap();'
      );
    });

    it('should generate an async query with no args and no result', () => {
      const result = parseFunctions({
        queries: [['helloWorld', {handler: async () => {}}]],
        updates: []
      });

      expect(result).toContain('#[ic_cdk::query]');
      expect(result).toContain('async fn app_hello_world()');
      expect(result).toContain('execute_async_function::<NoArgs, NoResult>("helloWorld", None)');
    });

    it('should generate a sync query with args and result', () => {
      const ArgsSchema = z.object({value: z.string()});
      const ResultSchema = z.object({text: z.string()});

      const result = parseFunctions({
        queries: [
          [
            'helloWorld',
            {
              args: ArgsSchema,
              result: ResultSchema,
              handler: (_args: any) => ({text: 'hello'})
            }
          ]
        ],
        updates: []
      });

      expect(result).toContain('#[ic_cdk::query]');
      expect(result).toContain(
        'fn app_hello_world(args: AppHelloWorldArgs) -> AppHelloWorldResult'
      );
      expect(result).toContain('execute_sync_function("helloWorld", Some(args))');
      expect(result).toContain(
        `${DERIVES}\npub struct AppHelloWorldArgs {\n    pub value: String,\n}`
      );
      expect(result).toContain(
        `${DERIVES}\npub struct AppHelloWorldResult {\n    pub text: String,\n}`
      );
    });

    it('should generate an async query with args and result', () => {
      const ArgsSchema = z.object({value: z.string()});
      const ResultSchema = z.object({text: z.string()});

      const result = parseFunctions({
        queries: [
          [
            'helloWorld',
            {
              args: ArgsSchema,
              result: ResultSchema,
              handler: async (_args: any) => ({text: 'hello'})
            }
          ]
        ],
        updates: []
      });

      expect(result).toContain('#[ic_cdk::query]');
      expect(result).toContain(
        'async fn app_hello_world(args: AppHelloWorldArgs) -> AppHelloWorldResult'
      );
      expect(result).toContain('execute_async_function("helloWorld", Some(args))');
      expect(result).toContain(
        `${DERIVES}\npub struct AppHelloWorldArgs {\n    pub value: String,\n}`
      );
      expect(result).toContain(
        `${DERIVES}\npub struct AppHelloWorldResult {\n    pub text: String,\n}`
      );
    });

    it('should generate a sync query with result only', () => {
      const ResultSchema = z.object({text: z.string()});

      const result = parseFunctions({
        queries: [
          [
            'helloWorld',
            {
              result: ResultSchema,
              handler: () => ({text: 'hello'})
            }
          ]
        ],
        updates: []
      });

      expect(result).toContain('fn app_hello_world() -> AppHelloWorldResult');
      expect(result).toContain(
        'execute_sync_function::<NoArgs, AppHelloWorldResult>("helloWorld", None)'
      );
    });

    it('should generate an async query with result only', () => {
      const ResultSchema = z.object({text: z.string()});

      const result = parseFunctions({
        queries: [
          [
            'helloWorld',
            {
              result: ResultSchema,
              handler: async () => ({text: 'hello'})
            }
          ]
        ],
        updates: []
      });

      expect(result).toContain('async fn app_hello_world() -> AppHelloWorldResult');
      expect(result).toContain(
        'execute_async_function::<NoArgs, AppHelloWorldResult>("helloWorld", None)'
      );
    });
  });

  describe('update', () => {
    it('should generate a sync update with no args and no result', () => {
      const result = parseFunctions({
        queries: [],
        updates: [['yolo', {handler: () => {}}]]
      });

      expect(result).toContain('#[ic_cdk::update]');
      expect(result).toContain('fn app_yolo()');
      expect(result).toContain(
        'execute_sync_function::<NoArgs, NoResult>("yolo", None).unwrap_or_trap();'
      );
    });

    it('should generate an async update with no args and no result', () => {
      const result = parseFunctions({
        queries: [],
        updates: [['yolo', {handler: async () => {}}]]
      });

      expect(result).toContain('#[ic_cdk::update]');
      expect(result).toContain('async fn app_yolo()');
      expect(result).toContain('execute_async_function::<NoArgs, NoResult>("yolo", None)');
    });

    it('should generate a sync update with args and result', () => {
      const ArgsSchema = z.object({value: z.string()});
      const ResultSchema = z.object({caller: j.principal()});

      const result = parseFunctions({
        queries: [],
        updates: [
          [
            'welcome',
            {
              args: ArgsSchema,
              result: ResultSchema,
              handler: (_args: any) => ({caller: {} as any})
            }
          ]
        ]
      });

      expect(result).toContain('#[ic_cdk::update]');
      expect(result).toContain('fn app_welcome(args: AppWelcomeArgs) -> AppWelcomeResult');
      expect(result).toContain('execute_sync_function("welcome", Some(args))');
      expect(result).toContain(
        `${DERIVES}\npub struct AppWelcomeArgs {\n    pub value: String,\n}`
      );
      expect(result).toContain('pub caller: Principal');
    });

    it('should generate an async update with args and result', () => {
      const ArgsSchema = z.object({value: z.string()});
      const ResultSchema = z.object({caller: j.principal()});

      const result = parseFunctions({
        queries: [],
        updates: [
          [
            'welcome',
            {
              args: ArgsSchema,
              result: ResultSchema,
              handler: async (_args: any) => ({caller: {} as any})
            }
          ]
        ]
      });

      expect(result).toContain('#[ic_cdk::update]');
      expect(result).toContain('async fn app_welcome(args: AppWelcomeArgs) -> AppWelcomeResult');
      expect(result).toContain('execute_async_function("welcome", Some(args))');
      expect(result).toContain(
        `${DERIVES}\npub struct AppWelcomeArgs {\n    pub value: String,\n}`
      );
      expect(result).toContain('pub caller: Principal');
    });

    it('should generate a sync update with result only', () => {
      const ResultSchema = z.object({value: z.bigint()});

      const result = parseFunctions({
        queries: [],
        updates: [
          [
            'welcome_without_args',
            {
              result: ResultSchema,
              handler: () => ({value: 123n})
            }
          ]
        ]
      });

      expect(result).toContain('fn app_welcome_without_args() -> AppWelcome_without_argsResult');
      expect(result).toContain(
        'execute_sync_function::<NoArgs, AppWelcome_without_argsResult>("welcome_without_args", None)'
      );
    });

    it('should generate an async update with result only', () => {
      const ResultSchema = z.object({value: z.bigint()});

      const result = parseFunctions({
        queries: [],
        updates: [
          [
            'welcome_without_args',
            {
              result: ResultSchema,
              handler: async () => ({value: 123n})
            }
          ]
        ]
      });

      expect(result).toContain(
        'async fn app_welcome_without_args() -> AppWelcome_without_argsResult'
      );
      expect(result).toContain(
        'execute_async_function::<NoArgs, AppWelcome_without_argsResult>("welcome_without_args", None)'
      );
    });
  });

  describe('convertCamelToSnake', () => {
    it('should convert camelCase to snake_case via generated fn name', () => {
      const result = parseFunctions({
        queries: [['helloWorld', {handler: () => {}}]],
        updates: []
      });
      expect(result).toContain('fn app_hello_world()');
    });

    it('should keep already snake_case names as is', () => {
      const result = parseFunctions({
        queries: [],
        updates: [['welcome_without_args', {handler: async () => {}}]]
      });
      expect(result).toContain('fn app_welcome_without_args()');
    });
  });

  describe('guard', () => {
    it('should generate a guard function and annotate the query when guard is provided', () => {
      const result = parseFunctions({
        queries: [['helloWorld', {handler: () => {}, guard: () => {}}]],
        updates: []
      });

      expect(result).toContain('#[ic_cdk::query(guard = "app_hello_world_guard")]');
      expect(result).toContain('fn app_hello_world_guard() -> Result<(), String>');
      expect(result).toContain('execute_guard("helloWorld")');
    });

    it('should generate a guard function and annotate the update when guard is provided', () => {
      const result = parseFunctions({
        queries: [],
        updates: [['yolo', {handler: () => {}, guard: () => {}}]]
      });

      expect(result).toContain('#[ic_cdk::update(guard = "app_yolo_guard")]');
      expect(result).toContain('fn app_yolo_guard() -> Result<(), String>');
      expect(result).toContain('execute_guard("yolo")');
    });

    it('should not generate a guard when none is provided', () => {
      const result = parseFunctions({
        queries: [['helloWorld', {handler: () => {}}]],
        updates: []
      });

      expect(result).not.toContain('fn app_yolo_guard()');
    });
  });
});
