#!/usr/bin/env bash
set -eux

: Update the package.json version before build and publish
node ./scripts/update-version.mjs utils
node ./scripts/update-version.mjs cli-tools
node ./scripts/update-version.mjs config
node ./scripts/update-version.mjs config-loader
node ./scripts/update-version.mjs storage
node ./scripts/update-version.mjs core
node ./scripts/update-version.mjs admin
node ./scripts/update-version.mjs analytics
node ./scripts/update-version.mjs console
node ./scripts/update-version.mjs core-peer

: Now we can build
npm run build --workspaces
