#!/usr/bin/env bash

function rm_ic_mgmt() {
  local package=$1

  npm rm @icp-sdk/canisters --workspace=packages/"$package"
}

function install_ic_mgmt_peer() {
  local package=$1

  npm i @icp-sdk/canisters --workspace=packages/"$package" --save-peer
}

function rm_utils() {
  local package=$1

  npm rm @dfinity/utils --workspace=packages/"$package"
}

function install_utils() {
  local package=$1

  npm i @dfinity/utils --workspace=packages/"$package"
}

function install_utils_peer() {
  local package=$1

  npm i @dfinity/utils --workspace=packages/"$package" --save-peer
}

PACKAGES_IC_MGMT_PEER=admin,cdn
PACKAGES_UTILS_PEER=admin,auth,cdn,functions,core,core-peer,cli-tools,did-tools,utils,storage,ic-client
PACKAGES_UTILS=core-standalone

for package in $(echo $PACKAGES_IC_MGMT_PEER | sed "s/,/ /g"); do
  rm_ic_mgmt "$package"
done

for package in $(echo $PACKAGES_UTILS_PEER | sed "s/,/ /g"); do
  rm_utils "$package"
done

for package in $(echo $PACKAGES_UTILS | sed "s/,/ /g"); do
  rm_utils "$package"
done

./scripts/update-agent

for package in $(echo $PACKAGES_IC_MGMT_PEER | sed "s/,/ /g"); do
  install_ic_mgmt_peer "$package"
done

for package in $(echo $PACKAGES_UTILS_PEER | sed "s/,/ /g"); do
  install_utils_peer "$package"
done

for package in $(echo $PACKAGES_UTILS | sed "s/,/ /g"); do
  install_utils "$package"
done