#!/usr/bin/env bash

function rm_agent() {
  local package=$1

  npm rm @dfinity/agent @dfinity/identity @dfinity/principal @dfinity/auth-client --workspace=packages/"$package"
}

function install_agent_dev() {
  local package=$1

  npm i @dfinity/agent@latest @dfinity/identity@latest @dfinity/principal@latest @dfinity/auth-client@latest --workspace=packages/"$package" --save-dev
}

function install_agent_peer() {
  local package=$1

  npm i @dfinity/agent@latest @dfinity/identity@latest @dfinity/principal@latest --workspace=packages/"$package" --save-peer
}

PACKAGES=core
PACKAGES_PEER=admin,ledger

# Remove agent-js libraries from all packages first to avoid resolve conflicts between those
for package in $(echo $PACKAGES | sed "s/,/ /g"); do
  rm_agent "$package"
done

for package in $(echo $PACKAGES_PEER | sed "s/,/ /g"); do
  rm_agent "$package"
done

for package in $(echo $PACKAGES | sed "s/,/ /g"); do
  install_agent_dev "$package"
done

for package in $(echo $PACKAGES_PEER | sed "s/,/ /g"); do
  install_agent_peer "$package"
done