#!/usr/bin/env bash

function rm_ic_mgmt() {
  local package=$1

  npm rm @icp-sdk/canisters --workspace=packages/"$package"
}

function install_ic_mgmt_peer() {
  local package=$1

  npm i @icp-sdk/canisters --workspace=packages/"$package" --save-peer
}

function rm_utils() {
  local package=$1

  npm rm @dfinity/utils --workspace=packages/"$package"
}

function install_utils() {
  local package=$1

  npm i @dfinity/utils --workspace=packages/"$package"
}

function install_utils_peer() {
  local package=$1

  npm i @dfinity/utils --workspace=packages/"$package" --save-peer
}

function rm_zod_schemas() {
  local package=$1

  npm rm @dfinity/zod-schemas --workspace=packages/"$package"
}

function install_zod_schemas() {
  local package=$1

  npm i @dfinity/zod-schemas --workspace=packages/"$package"
}

PACKAGES_IC_MGMT_PEER=admin,cdn
PACKAGES_UTILS_PEER=admin,auth,cdn,core,core-peer,utils,storage,ic-client,functions,cli-tools,functions-tools
PACKAGES_UTILS=core-standalone
PACKAGES_ZOD_SCHEMAS=zod

for package in $(echo $PACKAGES_IC_MGMT_PEER | sed "s/,/ /g"); do
  rm_ic_mgmt "$package"
done

for package in $(echo $PACKAGES_UTILS_PEER | sed "s/,/ /g"); do
  rm_utils "$package"
done

for package in $(echo $PACKAGES_UTILS | sed "s/,/ /g"); do
  rm_utils "$package"
done

for package in $(echo $PACKAGES_ZOD_SCHEMAS | sed "s/,/ /g"); do
  rm_zod_schemas "$package"
done

./scripts/update-agent

for package in $(echo $PACKAGES_IC_MGMT_PEER | sed "s/,/ /g"); do
  install_ic_mgmt_peer "$package"
done

for package in $(echo $PACKAGES_UTILS_PEER | sed "s/,/ /g"); do
  install_utils_peer "$package"
done

for package in $(echo $PACKAGES_UTILS | sed "s/,/ /g"); do
  install_utils "$package"
done

for package in $(echo $PACKAGES_ZOD_SCHEMAS | sed "s/,/ /g"); do
  install_zod_schemas "$package"
done