#!/usr/bin/env bash

function rm_agent() {
  local package=$1

  npm rm @dfinity/agent @dfinity/identity @dfinity/principal @dfinity/auth-client --workspace=packages/"$package"
}

function install_agent() {
  local package=$1

  npm i @dfinity/agent@latest @dfinity/identity@latest @dfinity/principal@latest --workspace=packages/"$package" --save-peer
}

function install_auth_client() {
  local package=$1

  npm i @dfinity/auth-client@latest --workspace=packages/"$package" --save-peer
}

PACKAGES=core,admin,ledger
PACKAGES_AUTH_CLIENT=core

# Remove agent-js libraries from all packages first to avoid resolve conflicts between those
for package in $(echo $PACKAGES | sed "s/,/ /g"); do
  rm_agent "$package"
done

for package in $(echo $PACKAGES | sed "s/,/ /g"); do
  install_agent "$package"
done

for package in $(echo $PACKAGES_AUTH_CLIENT | sed "s/,/ /g"); do
  install_auth_client "$package"
done