export const mockTransformedCoreTS = `// This file was automatically generated by the Juno CLI.
// Any modifications may be overwritten.

/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck

import type {_SERVICE as SatelliteActor} from './satellite.did';
import type { Principal } from '@icp-sdk/core/principal';
import {idlFactory} from './satellite.factory.did.js';
import {getSatelliteExtendedActor} from '@junobuild/core';

const buildVersion = async (): Promise<string> => {
\tconst {build_version} = await getSatelliteExtendedActor<SatelliteActor>({
\t\tidlFactory
\t});

\treturn await build_version();
}

const helloWorldWorld = async (value0: Hello, value1: string, value2: bigint): Promise<Result> => {
\tconst {hello_world_world} = await getSatelliteExtendedActor<SatelliteActor>({
\t\tidlFactory
\t});

\treturn await hello_world_world(value0, value1, value2);
}

const world = async (value0: Hello, value1: string): Promise<string> => {
\tconst {world} = await getSatelliteExtendedActor<SatelliteActor>({
\t\tidlFactory
\t});

\treturn await world(value0, value1);
}

const yolo = async (value0: Hello): Promise<string> => {
\tconst {yolo} = await getSatelliteExtendedActor<SatelliteActor>({
\t\tidlFactory
\t});

\treturn await yolo(value0);
}

const deleteErrors = async (value0: Array<string>): Promise<Result> => {
\tconst {delete_errors} = await getSatelliteExtendedActor<SatelliteActor>({
\t\tidlFactory
\t});

\treturn await delete_errors(value0);
}

export const functions = {
\tbuildVersion,
\thelloWorldWorld,
\tworld,
\tyolo,
\tdeleteErrors
};`;

export const mockTransformedCoreJS = `// This file was automatically generated by the Juno CLI.
// Any modifications may be overwritten.

/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck

import {idlFactory} from './satellite.factory.did.js';
import {getSatelliteExtendedActor} from '@junobuild/core';

const buildVersion = async () => {
\tconst {build_version} = await getSatelliteExtendedActor({
\t\tidlFactory
\t});

\treturn await build_version();
}

const helloWorldWorld = async (value0, value1, value2) => {
\tconst {hello_world_world} = await getSatelliteExtendedActor({
\t\tidlFactory
\t});

\treturn await hello_world_world(value0, value1, value2);
}

const world = async (value0, value1) => {
\tconst {world} = await getSatelliteExtendedActor({
\t\tidlFactory
\t});

\treturn await world(value0, value1);
}

const yolo = async (value0) => {
\tconst {yolo} = await getSatelliteExtendedActor({
\t\tidlFactory
\t});

\treturn await yolo(value0);
}

const deleteErrors = async (value0) => {
\tconst {delete_errors} = await getSatelliteExtendedActor({
\t\tidlFactory
\t});

\treturn await delete_errors(value0);
}

export const functions = {
\tbuildVersion,
\thelloWorldWorld,
\tworld,
\tyolo,
\tdeleteErrors
};`;
