name: Prepare

description: Checkout and install dependencies

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: lts/Hydrogen
    - name: Install dependencies
      shell: bash
      run: npm ci
