name: Prepare

description: Checkout and install dependencies

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Install npm
      shell: bash
      run: npm install -g npm
    - name: Install dependencies
      shell: bash
      run: npm ci
